<?php

namespace codemonster\logphp;

/**
 * Test class for ConsoleLogger.
 * Generated by PHPUnit on 2011-12-09 at 00:25:17.
 */
class ConsoleLoggerTest extends LoggerTest
{

    /**
     * @var ConsoleLogger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $config = new config\LoggerConfig();
        $this->object = new ConsoleLogger($config);
    }

    public function testEmerg()
    {
        $this->expectOutputRegex('/emergency message/');
        parent::testEmerg();
    }

    public function testAlert()
    {
        $this->expectOutputRegex('/alert message/');
        parent::testAlert();
    }

    public function testCrit()
    {
        $this->expectOutputRegex('/critical message/');
        parent::testCrit();
    }

    public function testErr()
    {
        $this->expectOutputRegex('/error message/');
        parent::testErr();
    }

    public function testNotice()
    {
        $this->expectOutputRegex('/notice message/');
        parent::testNotice();
    }

    public function testInfo()
    {
        $this->expectOutputRegex('/info message/');
        parent::testInfo();
    }

    public function testDebug()
    {
        $this->expectOutputRegex('/debug message/');
        parent::testDebug();
    }

    public function testDoLog()
    {
        parent::testLog();
    }

}
