<?php

namespace codemonster\logphp;

/**
 * Test class for LoggerException.
 * Generated by PHPUnit on 2011-12-09 at 21:45:27.
 */
class LoggerExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testConstruct()
    {
        $this->setExpectedException('\\codemonster\\logphp\\LoggerException',
                'Test exception', 99);
        throw new LoggerException('Test exception', 99);
    }

}