<?php

namespace codemonster\logphp;

use codemonster\logphp\Priority;

/**
 * Test class for LoggerWrapper.
 * Generated by PHPUnit on 2011-12-09 at 00:46:52.
 */
class LoggerWrapperTest extends ConsoleLoggerTest
{

    /**
     * @var LoggerWrapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $config = new config\LoggerConfig();
        $logger = new LoggerWrapperTestClass();
        $this->object = new LoggerWrapper($logger, $config);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testDoLog()
    {
        parent::testDoLog();
    }

}

/**
 * Test class for LoggerWrapperTest.
 */
class LoggerWrapperTestClass implements ILogger
{

    public function log($message, $priority)
    {
        printf('[%s] %s%s', Priority::getPriorityName($priority), $message,
                PHP_EOL);
        return true;
    }

}
