<?php

namespace codemonster\logphp;

use codemonster\logphp\Priority;

/**
 * Test class for NoLogger.
 * Generated by PHPUnit on 2011-12-08 at 23:50:35.
 */
class NoLoggerTest extends LoggerTest
{

    protected function setUp()
    {
        parent::setUp();
        $config = new config\LoggerConfig();
        $this->object = new NoLogger($config);
    }

    public function testDoLog()
    {
        $this->expectOutputString('');
        parent::testDoLog();
    }

}