<?php

namespace codemonster\logphp;

/**
 * Test class for Priority.
 * Generated by PHPUnit on 2011-12-08 at 23:41:46.
 */
class PriorityTest extends \PHPUnit_Framework_TestCase
{

    public function testIsValidPriority()
    {
        self::assertTrue(Priority::isValidPriority(Priority::ALERT));
        self::assertTrue(Priority::isValidPriority(Priority::CRIT));
        self::assertTrue(Priority::isValidPriority(Priority::ERR));
        self::assertTrue(Priority::isValidPriority(Priority::WARNING));
        self::assertTrue(Priority::isValidPriority(Priority::NOTICE));
        self::assertTrue(Priority::isValidPriority(Priority::INFO));
        self::assertTrue(Priority::isValidPriority(Priority::DEBUG));

        self::assertFalse(Priority::isValidPriority(99));
        self::assertFalse(Priority::isValidPriority('test'));
    }

    public function testGetPriorityName()
    {
        self::assertTrue(Priority::getPriorityName(Priority::ALERT) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::CRIT) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::ERR) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::WARNING) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::NOTICE) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::INFO) !== false);
        self::assertTrue(Priority::getPriorityName(Priority::DEBUG) !== false);

        self::assertTrue(Priority::getPriorityName(99) === false);
        self::assertTrue(Priority::isValidPriority('test') === false);
    }

}