<?php

namespace codemonster\logphp\config;

/**
 * Test class for config Exception.
 * Generated by PHPUnit on 2011-12-09 at 21:45:27.
 */
class LoggerConfigExceptionTest extends \PHPUnit_Framework_TestCase
{

    public function testConstruct()
    {
        $this->setExpectedException(
                '\\codemonster\\logphp\\config\\LoggerConfigException',
                'Test exception', 99);
        throw new LoggerConfigException('Test exception', 99);
    }

    public function testConstructBase()
    {
        $this->setExpectedException('\\codemonster\\logphp\\LoggerException',
                'Test exception', 99);
        throw new LoggerConfigException('Test exception', 99);
    }

}